package root.demo.model.repo;

public enum ArticleStatus {
	SUBMITTED,  
	IRRELEVANT_BY_TOPIC, 
	WAITING_FOR_REVIEW, 
	IRRELEVANT_BY_TEXT, 
	ADD_ADDITIONAL_EDITOR,
	MINOR_CHANGES, 
	MAJOR_CHANGES,
	REJECTED_TECHNICAL_REASON,
	REJECTED, 
	ACCEPTED
}
